# Generated by Django 3.0.4 on 2020-03-07 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200307_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name': 'Тред', 'verbose_name_plural': 'Треды'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='thread',
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
