# Generated by Django 3.0.4 on 2020-03-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200307_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='article_text',
            new_name='thread_text',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='article_title',
            new_name='thread_title',
        ),
        migrations.AddField(
            model_name='board',
            name='board_name',
            field=models.CharField(default='Доска', max_length=200, verbose_name='Название доски'),
            preserve_default=False,
        ),
    ]
