# Generated by Django 3.0.4 on 2020-03-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200307_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_text',
            field=models.TextField(verbose_name='Текст треда'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_title',
            field=models.CharField(max_length=200, verbose_name='Название треда'),
        ),
    ]
