# Generated by Django 3.0.4 on 2020-03-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200307_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_path',
            field=models.CharField(default='board', max_length=200, verbose_name='Путь к доске'),
            preserve_default=False,
        ),
    ]
